version: '3.0'

services:
    lumen-app:
      build: .
      container_name: lumen-app
      restart: always
      volumes:
        - "./:/app"
      working_dir: /app
      command: "sh ./startup.sh"
      ports:
        - 7000:7000
      network_mode: host
      # networks:
      #   - local-net

# networks:
#   local-net:
#     external:
#       name: local-net